title: Dustup - docs
description: Dustup - docs

theme: just-the-docs

url: https://dustup-gg.github.io/docs

aux_links:
  "Ask your questions on Discord":
    - "https://discord.gg/Zx37vEkzzB"
color_scheme: dustup
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: yellow
  tip:
    title: Tip
    color: blue