title: Dustup help centre
description: Dustup help centre

theme: just-the-docs

url: https://dustup-gg.github.io/docs

aux_links:
  "Ask your questions on Discord":
    - "https://discord.gg/Zx37vEkzzB"
color_scheme: dustup
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: yellow
  tip:
    title: Tip
    color: blue

# Set a path/url to a logo that will be displayed instead of the title
logo: "/images/dustup-logo.png"
